= Unified Style Guide: Special Files {revnum}
:revnum: 0.1
:numbered:
:toc2:

== Introduction
This document is provides guidelines for special file usage and structure. Following these guidelines should provide the following benefits:

  - Promote consistent special file usage.
  - Aid organization of information.

=== Archive Information
These files are used to provide information about the contents of an archive. An archive is typically a zip file (although other similar formats may be used) that is simply used to archive other files. All archives must contain a archive information file named `+__arc_info__.txt+` in base directory. The file is formatted using AsciiDoc markup.

.Example `+__arc_info__.txt+` file for archive named `archive_example.zip`
--------
= archive_example <1>
:date: 1 January 2013

This archive contains some example files.
--------

<1> Title is the name of the archive file (without extension).

=== Changelog Files
These files are used to maintain the changes to a project or set of files. These files are always named either `changelog.<ext>` or `CHANGLOG.<ext>` and the extension will typically either be `.adoc` or `.txt` for AsciiDoc or `.md` for Markdown.

=== Directory Information
These files are used to provide additional information on the use or purpose of a directory. These files are always named `+__dir_info__.txt+` and are only applicable to the parent directory. These files are formatted using AsciiDoc markup.

.Example `+__dir_info__.txt+` file for directory named `ExampleDirectory/`
--------
= ExampleDirectory <1>
:date: 1 January 2013

This directory contains some example files.
--------

<1> Title is the name of the parent directory.

=== External Files
These files are used to indicate that the contents of a directory are sourced or directly copied for a different location. These files are always named `+__ext_files__.txt+` and only applicable to the parent directory.

=== Readme Files
These files are used to provide reference information for a project. These files are always named either `readme.<ext>` or `README.<ext>` and the extension will typically either be `.adoc` or `.txt` for AsciiDoc or `.md` for Markdown.

The following sections are common (omit those not applicable):

  - Introduction - Quick introduction to the project. Explain what it is, the functionality, and use domain.
  - Status - Current status of project and changelog.
  - License - Copy/license information.
  - Requirements - Required items for the project to function.
  - Installation - Procedure to install project.
  - Usage - Quick explanation of project usage, examples if library and quick tips if application.
  - Documentation - Additional project documentation.
  - Standards - List any standards (naming, versioning, etc) used by the project.
  - Issues - List of known issues/bugs.
  - Contacts - Information for contacting project maintainers.
  - Contributing - Information for contributing to the project.
  - Similar - Reference information about similar projects.
  - FAQ - Answers to questions not answered in other sections.

==== Status Section
The following boilerplate text is recommended for the project status:

  - The status of this project is **planning**. This project is not yet suitable for use.
  - The status of this project is **pre-alpha**. This project is not yet suitable for use other than testing.
  - The status of this project is **alpha**. This project is not yet suitable for use other than testing.
  - The status of this project is **beta**. This project is suitable for use but there may be incompatibilities in new releases.
  - The status of this project is **production/stable**. This project is suitable for use and new releases will maintain compatibility unless otherwise stated.
  - The status of this project is **mature**. This project is suitable for use and new releases will only address critical issues (e.g. bug fixes).
  - The status of this project is **inactive**. This project is suitable for use but no new releases are planned.

=== See Also File
These files are used to provide locations of information relevant to the parent directory's contents. These files are always named `+__see_also__.txt+` and are only applicable to the parent directory. These files are formatted using AsciiDoc markup.

=== User Scripts
These files are scripts intended for direct interactive with a user; typically the user will begin the interaction by executing the script directly (rather than it being called by another script or utility). These files are named using the following convention:

  - Leading underscore.
  - First word is a strong verb.
  - Remaining words describe script action.
  - Typically no longer than four words.
  - Capitalize the first letter of each word.
  - Separate words with an underscore.
  - Extension is based on the script type.

See the following examples:

  - `_Cleanup.bat`
  - `_Build_HTML.py`
  - `_Start_Test_Server.sh`
