= Unified Style Guide: Files and Directories {revnum}
:revnum: 0.1
:numbered:
:toc2:

// Versioned using `http://www.nidcr.nih.gov/Research/ToolsforResearchers/Toolkit/VersionControlGuidelines.htm` convention.

== Introduction
This document provides guidelines for naming computer files and directories. Following these guidelines should provide the following benefits:

  - Promote a consistent style over various use cases.
  - Aid organization of information.
  - Eliminate issues due to whitespace in file paths.

== File Naming
Files use lowercase_underscore notation. All files should include an extension with the only exceptions being files that follow well established and software dependent conventions (e.g. `Makefile`). The extension should always be lowercase. See the following examples:

  - `sample_file.txt`
  - `file_with_a_longer_name.jpg`

When numbers are used to differentiate between files with similar names, the number should follow the name with a hyphen in between. See the following examples:

  - `some_file-1.jpg`
  - `some_file-2.jpg`
  - `some_file-3.jpg`

Any additional metadata added to the filename should prefix the proper name and be delimited with a hyphen. Metadata can be changed together and date information will typically go first. See the following examples:

  - `followup-some_doc.txt` - The `followup` text is metadata.
  - `under_review-some_doc.txt` - The `under_review` text is metadata.
  - `20120101-under_review-some_doc.txt` - The `under_review` text is metadata.

When dates are added to the filename, they should use the `YYYYMMDD` format and be prefixed to the filename and delimited with a hyphen. If the time is also included, use the `YYYYMMDDhhmm` format with the hours and minutes being 24-hour. If necessary second and milliseconds could be added in the same fashion although this case should rarely be used. See the following examples:

  - `20120101-my_file.txt` - 1 January 2012
  - `201201012030-my_file.txt` - 1 January 2012 at 8:30pm

To describe a file that contains information over a range of dates, use `_to_` to delimit the dates. See the following examples:

  - `20120101_to_20121012-finances.txt` - 1 January 2012 through 12 October 2012

Filenames may contain capital letters when necessary for a specific use. See the following examples:

  - `Makefile` - Capital M by standard convention
  - `_Build_All.bat` - Capital letters and leading underscore by user convention.

Special metadata files use lowercase_underscore notation with double-underscores as prefix and postfix. See the following examples:

  - `__dir_info__.txt`
  - `__archive_info__.txt`

== Directory Naming
Directory types fall into three general categories:

  - *record* - Directory used to store files that generalize a broad category. Typically files that are direct children are not frequently modified.
  - *resource* - Directory used to store files that are frequently modified and
  - *special* - Function of these directories vary.

Record directories use LeadingCaps notation. See the following examples:

  - `TaxRecords/`
  - `VacationPhotos/`

Resource directories use lowercase_underscore notation. See the following examples:

  - `src/`
  - `html_templates/`

In either record or resource directories, hyphens are used to delimit date and other metadata applied as a prefix. See the following examples:

  - `2012-TaxRecords/`
  - `obsolete-css/`

Special directories use lowercase_underscore notation with double-underscores as prefix. Double-underscores are used as a postfix unless the special name is being used as a metadata prefix. See the following examples:

  - `__backup__/`
  - `__output__/`
  - `__output-log_files/`
  - `__temp__/`
  - `__temp-pictures/`

== Additional Guidelines
Special metadata prefixes can be added to a file or directory to give it additional meaning. These prefixes should be limited to one word with lowercase notation and leading double-underscores. See the following examples:

  - `__temp-my_file.txt` - Marks the file as temporary.
  - `__output-my_file.txt` - Marks the file as output.

Record directories may use metadata that follows the lowercase_underscore convention. See the following examples:

  - `under_review-TaxRecords/`

If necessary, record or resource directories can use a single underscore as a prefix to denote a differing level of significance from its sibling directories. See the following examples:

  - `_SomethingSpecial/`

If necessary, metadata can be applied as a postfix to files and directories. Typically, this is used to maintain alphabetical order of the proper name. See the following examples:

  - `TaxRecords-under_review/`

Unless necessary, avoid using additional periods in file or directory names. Periods are typically only used to separate the filename from the extension. A typical case that requires additional periods is when a version number is included in the file or directory name. See the following examples:

  - `my_file-0.1.0.txt`
  - `SomeProject-v1.2/`
