= Unified Style Guide: Projects {revnum}
:revnum: 0.1
:numbered:
:toc: left

== Introduction
This document provides guidelines for structuring and naming computer projects. Following these guidelines should provide the following benefits:

  - Promote a consistent style over various use cases.
  - Aide organization of files and information.

== Top-Level Project Directories
The project root is a record directory. The following subdirectories are typical in a project root:

  - `Concept/` - Files related to planning the project design.
  - `Design/` - Files related to the design of the project.
  - `Notes/` - Notes related to the project.
  - `Releases/` - Archives of project releases.

The following subdirectories may be used when applicable:

  - `Assignments/` - Maintains task or assignment files related to the project but limited in scope.
  - `Backup/` - Backups not maintained elsewhere.
  - `Records/` - Itemized records related to the project.
  - `References/` - Reference material received from other sources.

== Design Subdirectories
Inside the `Design/` directory, the contents are largely dependent on the project type.

=== Software Project
For software development projects, the following resource subdirectories may be used to structure the design files if applicable:

  - `app/` - Source code for the project application.
  - `doc/` - Documentation related to the project; can be handled by a source code extraction utility e.g. Doxygen.
  - `examples/` - Example usage of the software.
  - `install/` - Installation related files.
  - `lib/` - Source code for the project library.
  - `platform/` - Platform specific source code required by the application.
  - `tests/` - Unit tests and related files.
  - `utils/` - Various utilities used by the project application or library e.g. third-party libraries.
  - `www/` - Website related files.

== Example Project Structures
.Software Project
----
MyProject/
|-- Concept/
|   |-- brainstorming.txt
|-- Design/
    |-- app/
    |   |-- Makefile
    |   |-- main.c
    |   |-- main.h
    |-- doc/
    |   |-- usage.txt
    |-- changelog.txt
    |-- readme.txt
----
